// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hexwjpvbieriohnlwiqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhleHdqcHZiaWVyaW9obmx3aXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDE5ODAsImV4cCI6MjA3MjQxNzk4MH0.gefAr6_09X-D679NP5sSjSwH6DPsTX9ihOOZp59Axsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});